<div >
	<div style="background:#f4f4f4">
  
  <div style="background-color:#f4f4f4"><div style="margin:0px auto;max-width:600px"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:20px 0px 20px 0px"><div class="m_2371122331041453857mj-column-per-100" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-wrap:break-word;font-size:0px;padding:0px 0px 0px 25px;padding-top:0px;padding-bottom:0px" align="left"><div style="color:#55575d;font-family:Arial,sans-serif;font-size:11px;line-height:22px;text-align:left"><p style="font-size:13px;margin:10px 0"></p></div></td></tr></tbody></table></div></td></tr></tbody></table></div>
      <div style="margin:0px auto;max-width:600px"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:20px 0px;padding-bottom:0px;padding-top:0px"><div class="m_2371122331041453857mj-column-per-100" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-wrap:break-word;font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px" align="center"><table role="presentation" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0px" align="center" border="0"><tbody><tr><td style="width:600px"><img alt="" title="" style="display:block; margin: 0 auto" height="auto" src="https://parking.derco.com.pe/admin/logo.jfif" width="150" class="CToWUd a6T" data-bit="iit" tabindex="0"><div class="a6S" dir="ltr" style="opacity: 0.01; left: 838.5px; top: 176px;"><div id=":1s5" class="T-I J-J5-Ji aQv T-I-ax7 L3 a5q" role="button" tabindex="0" aria-label="Descargar el archivo adjunto " data-tooltip-class="a1V" data-tooltip="Descargar"><div class="akn"><div class="aSK J-J5-Ji aYr"></div></div></div></div></td></tr></tbody></table></td></tr></tbody></table></div></td></tr></tbody></table></div>
      <div style="margin:0px auto;max-width:600px;background:#ffffff"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%;background:#ffffff" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:20px 0px 20px 0px"><div class="m_2371122331041453857mj-column-per-100" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-wrap:break-word;font-size:0px;padding:0px 25px 0px 25px;padding-top:0px;padding-bottom:0px" align="left"><div style="color:#55575d;font-family:Arial,sans-serif;font-size:13px;line-height:22px;text-align:left"><h1 style="font-size:20px;font-weight:bold">
	  <span style="color:#57ce79">Hola,&nbsp;{{ $name }}</span>
	  </h1></div></td></tr><tr><td style="word-wrap:break-word;font-size:0px;padding:0px 25px 0px 25px;padding-top:0px;padding-bottom:0px" align="left"><div style="color:#55575d;font-family:Arial,sans-serif;font-size:13px;line-height:22px;text-align:left"><p style="font-size:13px;margin:10px 0">
	  <span style="font-size:14px">Dale click o copia el siguiente link en tu navegador para validar tu correo electrónico y poder hacer el cambio de tu contraseña:</span>
	  </p></div></td></tr><tr><td style="word-wrap:break-word;font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px" align="left"><div style="color:#55575d;font-family:Arial,sans-serif;font-size:13px;line-height:22px;text-align:left"><p style="font-size:13px;margin:10px 0">
	  <span style="font-size:14px"><i><b>
	  <a href="{{ $link }}" target="_blank" >{{ $link }}</a>
	  </b></i></span>
	  </p>
    </div>
</td></tr><tr><td style="word-wrap:break-word;font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px" align="left">
</td></tr><tr><td style="word-wrap:break-word;font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px" align="left">
<div style="color:#55575d;font-family:Arial,sans-serif;font-size:13px;line-height:24px;text-align:left"><p style="font-size:13px;line-height:12px;margin:10px 0">&nbsp;</p><p style="font-size:13px;line-height:12px;margin:10px 0"><span style="font-size:14px"><span style="color:#606060"></span></span></p><p style="font-size:13px;line-height:12px;margin:10px 0"><span style="font-size:14px"><b><span style="color:#606060">Gerente de Personas y Transformación</span></b></span></p><p style="font-size:13px;line-height:12px;margin:10px 0">&nbsp;</p></div></td></tr></tbody></table></div></td></tr></tbody></table></div>
      <div style="margin:0px auto;max-width:600px"><table role="presentation" cellpadding="0" cellspacing="0" style="font-size:0px;width:100%" align="center" border="0"><tbody><tr><td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:20px 0px;padding-top:5px"><div class="m_2371122331041453857mj-column-per-100" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%"><table role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0"><tbody><tr><td style="word-wrap:break-word;font-size:0px;padding:10px 25px;padding-top:0px;padding-bottom:0px" align="left"><div style="color:#55575d;font-family:Arial,sans-serif;font-size:13px;line-height:24px;text-align:left"><p style="font-size:13px;line-height:19px;margin:10px 0;text-align:center">


	  </p></div></td></tr></tbody></table></div></td></tr></tbody></table></div></div>

<br><img src="https://ci3.googleusercontent.com/proxy/xbNNm-i5zA35MTx4g-8xxDkPD3c5a8VxU7FVTVDTreX3YUOhgvY4ig9V3_XAI7YdKTsG169efC7M1FBoU4PGbpULjgHotFsU_BtgmN95o4VZtG2MHWDFbsmEYQUFSc8cRkhtjQvzf-BmALCLgcYP2HlCoxEZ8XE3eV2UGfXupd28EPIr4F9E=s0-d-e1-ft#http://j9px.mjt.lu/oo/APsAABaABooAAAAAAAAAAACHYvgAAAAAPo4AAAAAAAkNvQBbseWCSx7sENzATs-iem6B3Rp3pAAIljY/54881688/e.gif" height="1" width="1" alt="" border="0" style="height:1px;width:1px;border:0" class="CToWUd" data-bit="iit" jslog="138226; u014N:xr6bB; 53:W2ZhbHNlLDJd"><div class="yj6qo"></div><div class="adL">
</div></div>
</div>